### ISSUE TITLE
Error When Running the dev-server Script for development

### ISSUE THREAD

**Issue by ogbiyoyosky** [stonecoinproject/stonem-frontend#28]
### How to reproduce

# Environment 
- node -v 8.14

1 git clone https://github.com/stonecoinproject/stonem-frontend.git

2 Run yarn install to install dependency

3 Run yarn run dev-server

Error on compiling project.

![image](https://user-images.githubusercontent.com/34397562/49736089-10584080-fc81-11e8-8e83-31a02d7ff474.png)

**Comment by creatrixity** [comment]
This error occurs due to the inability to properly resolve type definitions for Styled Components/Rebass . Fixed in #30
